In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("Bengaluru_House_Data.csv")

In [3]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
df.info

<bound method DataFrame.info of                   area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II
1                Plot  Area  Ready To Move          Chikka Tirupathi
2            Built-up  Area  Ready To Move               Uttarahalli
3      Super built-up  Area  Ready To Move        Lingadheeranahalli
4      Super built-up  Area  Ready To Move                  Kothanur
...                     ...            ...                       ...
13315        Built-up  Area  Ready To Move                Whitefield
13316  Super built-up  Area  Ready To Move             Richards Town
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar
13318  Super built-up  Area         18-Jun           Padmanabhanagar
13319  Super built-up  Area  Ready To Move              Doddathoguru

            size  society total_sqft  bath  balcony   price
0          2 BHK  Coomee        1056   2.0      1.0   39.07
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00
2          3 BHK      NaN       1440   2.0      3.0   62.00
3          3 BHK  Soiewre       1521   3.0      1.0   95.00
4          2 BHK      NaN       1200   2.0      1.0   51.00
...          ...      ...        ...   ...      ...     ...
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00
13316      4 BHK      NaN       3600   5.0      NaN  400.00
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00
13319      1 BHK      NaN        550   1.0      1.0   17.00

[13320 rows x 9 columns]>

In [5]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [6]:
df.drop(columns=['society'], inplace=True)

In [7]:
df['bhk']=df['size'].str.extract(r'(\d+)').astype(float)

In [8]:
df.drop(columns=['size'],inplace=True)

In [9]:
df.isnull().sum()

area_type         0
availability      0
location          1
total_sqft        0
bath             73
balcony         609
price             0
bhk              16
dtype: int64

In [10]:
df[df['total_sqft'].astype(str).str.contains('-')]

,area_type,availability,location,total_sqft,bath,balcony,price,bhk
30,Super built-up Area,19-Dec,Yelahanka,2100 - 2850,4.0,0.0,186.000,4.0
56,Built-up Area,20-Feb,Devanahalli,3010 - 3410,NaN,NaN,192.000,4.0
81,Built-up Area,18-Oct,Hennur Road,2957 - 3450,NaN,NaN,224.500,4.0
122,Super built-up Area,18-Mar,Hebbal,3067 - 8156,4.0,0.0,477.000,4.0
137,Super built-up Area,19-Mar,8th Phase JP Nagar,1042 - 1105,2.0,0.0,54.005,2.0
...,...,...,...,...,...,...,...,...
12990,Super built-up Area,18-May,Talaghattapura,1804 - 2273,3.0,0.0,122.000,3.0
13059,Super built-up Area,Ready To Move,Harlur,1200 - 1470,2.0,0.0,72.760,2.0
13240,Super built-up Area,Ready To Move,Devanahalli,1020 - 1130,NaN,NaN,52.570,1.0
13265,Super built-up Area,20-Sep,Hoodi,1133 - 1384,2.0,0.0,59.135,2.0
13299,Super built-up Area,18-Dec,Whitefield,2830 - 2882,5.0,0.0,154.500,4.0

In [11]:
print(df[df['total_sqft'].astype(str).str.contains('-')].shape[0])

201

In [12]:
def convert_sqft(x):
    x = str(x)
    if '-' in x:
        parts = x.split('-')
        return (float(parts[0]) + float(parts[1])) / 2
    try:
        return float(x)
    except:
        return None

df['total_sqft'] = df['total_sqft'].apply(convert_sqft)

In [13]:
df['is_ready'] = (df['availability'] == 'Ready To Move').astype(int)

In [14]:
df.drop(columns=['availability'],inplace=True)

In [15]:
df

,area_type,location,total_sqft,bath,balcony,price,bhk,is_ready
0,Super built-up Area,Electronic City Phase II,1056.0,2.0,1.0,39.07,2.0,0
1,Plot Area,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4.0,1
2,Built-up Area,Uttarahalli,1440.0,2.0,3.0,62.00,3.0,1
3,Super built-up Area,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3.0,1
4,Super built-up Area,Kothanur,1200.0,2.0,1.0,51.00,2.0,1
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Whitefield,3453.0,4.0,0.0,231.00,5.0,1
13316,Super built-up Area,Richards Town,3600.0,5.0,NaN,400.00,4.0,1
13317,Built-up Area,Raja Rajeshwari Nagar,1141.0,2.0,1.0,60.00,2.0,1
13318,Super built-up Area,Padmanabhanagar,4689.0,4.0,1.0,488.00,4.0,0
13319,Super built-up Area,Doddathoguru,550.0,1.0,1.0,17.00,1.0,1

In [16]:
df.isnull().sum()

area_type       0
location        1
total_sqft     46
bath           73
balcony       609
price           0
bhk            16
is_ready        0
dtype: int64

In [17]:
df.dropna(inplace=True)
print(df.shape)

(12668, 8)

In [18]:
df.isnull().sum()

area_type     0
location      0
total_sqft    0
bath          0
balcony       0
price         0
bhk           0
is_ready      0
dtype: int64

In [19]:
df['location'] = df['location'].apply(lambda x: x.strip())
location_counts = df['location'].value_counts()
rare_locations = location_counts[location_counts < 10].index
df['location'] = df['location'].apply(lambda x: 'other' if x in rare_locations else x)

In [20]:
print(df.shape)
print(df['location'].nunique())

(12668, 8)
248

In [21]:
 print(df['location'].value_counts().tail(10))

location
Dairy Circle             10
Naganathapura            10
Nagappa Reddy Layout     10
Basapura                 10
Kalkere                  10
1st Block Koramangala    10
Thyagaraja Nagar         10
Gunjur Palya             10
Doddaballapur            10
HAL 2nd Stage            10
Name: count, dtype: int64

In [33]:

df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']

print("Before removing outliers:", df.shape)
print(df['price_per_sqft'].describe())  # see min, max, mean

Before removing outliers: (11994, 259)
count    11994.000000
mean       343.294858
std        108.061819
min         12.310676
25%        282.625455
50%        329.026712
75%        373.519598
max       1485.428827
Name: price_per_sqft, dtype: float64

In [34]:

df = df[df['price_per_sqft'] > 300]      
df = df[df['price_per_sqft'] < 50000]    
df = df[df['bath'] < df['bhk'] + 2]      

df.drop(columns=['price_per_sqft'], inplace=True)
print("After removing outliers:", df.shape)

After removing outliers: (8021, 258)

In [24]:
df = pd.get_dummies(df, columns=['location', 'area_type'])
print(df.shape)

(12513, 258)

In [25]:
df = df[df['price'] <= 300]
print(df.shape)
print(df['price'].describe())

(11994, 258)
count    11994.000000
mean        84.500554
std         54.356508
min          8.000000
25%         48.000000
50%         67.000000
75%        100.000000
max        300.000000
Name: price, dtype: float64

In [26]:
df['price'] = np.log1p(df['price'])

In [27]:
X = df.drop(columns=['price'])
y= df['price']

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape)

(9595, 257) (2399, 257)

In [29]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train, y_train)
print("Model trained successfully!")

Model trained successfully!

In [30]:
from sklearn.metrics import r2_score
import numpy as np
predictions = model.predict(X_test)
print("R² score:", round(r2_score(y_test, predictions), 2))

R² score: 0.75

In [31]:
model2 = RandomForestRegressor(n_estimators=200, random_state=42)
model2.fit(X_train, y_train)
pred2 = model2.predict(X_test)
print("R² score:", round(r2_score(y_test, pred2), 2))

R² score: 0.75

In [32]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predictions))
print(f"Average error: ₹{rmse:.2f} lakhs")

Average error: ₹0.29 lakhs

In [39]:
import pickle


with open('house_price_model.pkl', 'wb') as f:
    pickle.dump(model, f)


with open('columns.pkl', 'wb') as f:
    pickle.dump(list(X.columns), f)

print("Model saved!")
print("Number of features:", len(X.columns))

Model saved!
Number of features: 257

In [40]:
import os
print("model file size:", os.path.getsize('house_price_model.pkl'), "bytes")
print("columns file size:", os.path.getsize('columns.pkl'), "bytes")

model file size: 144943166 bytes
columns file size: 6228 bytes

In [41]:
import os
print(os.getcwd())

C:\Users\parde